version: "3"
services:
  node:
    restart: always
    build: .
    ports:
      - 4002:4002
    volumes:
      - ./:/code
    command: bash -c "/usr/wait-for-it.sh --timeout=0 mongo:27017 && npm run seed && npm run start"
  mongo:
    image: mongo
    ports:
      - 27018:27017
    volumes:
      - mongodb:/data/db
volumes:
  mongodb:
