version: 2.1

orbs:
  node: circleci/node@4.7

workflows:

jobs:
  build:
    docker:
      - image: circleci/node:14.15.4
      - image: circleci/mongo:4.4.1
    steps:
      - checkout
      - run:
          name: "env vars"
          command: |
            echo $cloud_name
            echo $api_key
            echo $api_secret
      - run:
          name: Install project dependencies
          command: npm ci
      - run:
          name: Seed database
          command: npm run seed
      - run:
          name: Run tests
          command: npm run test
